DROP DATABASE IF EXISTS comp3161_final_project;
CREATE DATABASE comp3161_final_project;
USE comp3161_final_project;

DROP TABLE IF EXISTS Courses;
CREATE TABLE Courses(
  `Course ID` VARCHAR(255) NOT NULL PRIMARY KEY,
  `Course Name` VARCHAR(255)
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students(
  `Student ID` VARCHAR(255) NOT NULL PRIMARY KEY,
  `First Name` VARCHAR(255),
  `Last Name` VARCHAR(255),
  Email VARCHAR(255),
  Age INTEGER,
  Birthday DATE,
  Password VARCHAR(255)
);

DROP TABLE IF EXISTS Lecturers;
CREATE TABLE Lecturers(
  `Lecturer ID` VARCHAR(255) NOT NULL PRIMARY KEY,
  `First Name` VARCHAR(255),
  `Last Name` VARCHAR(255),
  Email VARCHAR(255),
  Age INTEGER,
  Birthday DATE,
  Password VARCHAR(255)
);

DROP TABLE IF EXISTS `Course Students`;
CREATE TABLE `Course Students`(
  `Student ID` VARCHAR(255),
  `Course ID` VARCHAR(255),
  Grade INTEGER
);

DROP TABLE IF EXISTS `Course Lecturers`;
CREATE TABLE `Course Lecturers`(
  `Lecturer ID` VARCHAR(255),
  `Course ID` VARCHAR(255)
);

INSERT INTO Courses VALUES('FP0', 'Fundamentals in Python');
INSERT INTO Courses VALUES('FJ1', 'Fundamentals in Javascript');
INSERT INTO Courses VALUES('FC2', 'Fundamentals in C#');
INSERT INTO Courses VALUES('FJ3', 'Fundamentals in Java');
INSERT INTO Courses VALUES('FC4', 'Fundamentals in C');
INSERT INTO Courses VALUES('FC5', 'Fundamentals in C++');
INSERT INTO Courses VALUES('FP6', 'Fundamentals in PHP');
INSERT INTO Courses VALUES('FK7', 'Fundamentals in Kotlin');
INSERT INTO Courses VALUES('FR8', 'Fundamentals in R');
INSERT INTO Courses VALUES('FH9', 'Fundamentals in HTML');
INSERT INTO Courses VALUES('FC10', 'Fundamentals in CSS');
INSERT INTO Courses VALUES('FS11', 'Fundamentals in Swift');
INSERT INTO Courses VALUES('FG12', 'Fundamentals in GO');
INSERT INTO Courses VALUES('FR13', 'Fundamentals in Ruby');
INSERT INTO Courses VALUES('FP14', 'Fundamentals in Pascal');
INSERT INTO Courses VALUES('FD15', 'Fundamentals in Dart');
INSERT INTO Courses VALUES('FP16', 'Fundamentals in Pascal');
INSERT INTO Courses VALUES('FR17', 'Fundamentals in Rust');
INSERT INTO Courses VALUES('FC18', 'Fundamentals in Cobol');
INSERT INTO Courses VALUES('FC19', 'Fundamentals in Calculus');
INSERT INTO Courses VALUES('FC20', 'Fundamentals in Calculus');
INSERT INTO Courses VALUES('FE21', 'Fundamentals in Electronic Circuit Analysis');
INSERT INTO Courses VALUES('FS22', 'Fundamentals in Statistics');
INSERT INTO Courses VALUES('FC23', 'Fundamentals in Chemistry');
INSERT INTO Courses VALUES('FB24', 'Fundamentals in Biology');
INSERT INTO Courses VALUES('FP25', 'Fundamentals in Physics');
INSERT INTO Courses VALUES('FI26', 'Fundamentals in Information Technology');
INSERT INTO Courses VALUES('FC27', 'Fundamentals in Calculus 2');
INSERT INTO Courses VALUES('FE28', 'Fundamentals in Electronics');
INSERT INTO Courses VALUES('FP29', 'Fundamentals in Physical Education');
INSERT INTO Courses VALUES('FH30', 'Fundamentals in Health and Nutrition');
INSERT INTO Courses VALUES('FH31', 'Fundamentals in Home and Family Life Education');
INSERT INTO Courses VALUES('FC32', 'Fundamentals in Civics');
INSERT INTO Courses VALUES('FC33', 'Fundamentals in Carpentry');
INSERT INTO Courses VALUES('FW34', 'Fundamentals in Welding');
INSERT INTO Courses VALUES('FT35', 'Fundamentals in Telecommunications');
INSERT INTO Courses VALUES('FM36', 'Fundamentals in Machinery');
INSERT INTO Courses VALUES('FW37', 'Fundamentals in Web DEvelopement');
INSERT INTO Courses VALUES('FD38', 'Fundamentals in Database Management');
INSERT INTO Courses VALUES('FD39', 'Fundamentals in Discrete Mathematics');
INSERT INTO Courses VALUES('NP0', 'Novice Python');
INSERT INTO Courses VALUES('NJ1', 'Novice Javascript');
INSERT INTO Courses VALUES('NC2', 'Novice C#');
INSERT INTO Courses VALUES('NJ3', 'Novice Java');
INSERT INTO Courses VALUES('NC4', 'Novice C');
INSERT INTO Courses VALUES('NC5', 'Novice C++');
INSERT INTO Courses VALUES('NP6', 'Novice PHP');
INSERT INTO Courses VALUES('NK7', 'Novice Kotlin');
INSERT INTO Courses VALUES('NR8', 'Novice R');
INSERT INTO Courses VALUES('NH9', 'Novice HTML');
INSERT INTO Courses VALUES('NC10', 'Novice CSS');
INSERT INTO Courses VALUES('NS11', 'Novice Swift');
INSERT INTO Courses VALUES('NG12', 'Novice GO');
INSERT INTO Courses VALUES('NR13', 'Novice Ruby');
INSERT INTO Courses VALUES('NP14', 'Novice Pascal');
INSERT INTO Courses VALUES('ND15', 'Novice Dart');
INSERT INTO Courses VALUES('NP16', 'Novice Pascal');
INSERT INTO Courses VALUES('NR17', 'Novice Rust');
INSERT INTO Courses VALUES('NC18', 'Novice Cobol');
INSERT INTO Courses VALUES('NC19', 'Novice Calculus');
INSERT INTO Courses VALUES('NC20', 'Novice Calculus');
INSERT INTO Courses VALUES('NE21', 'Novice Electronic Circuit Analysis');
INSERT INTO Courses VALUES('NS22', 'Novice Statistics');
INSERT INTO Courses VALUES('NC23', 'Novice Chemistry');
INSERT INTO Courses VALUES('NB24', 'Novice Biology');
INSERT INTO Courses VALUES('NP25', 'Novice Physics');
INSERT INTO Courses VALUES('NI26', 'Novice Information Technology');
INSERT INTO Courses VALUES('NC27', 'Novice Calculus 2');
INSERT INTO Courses VALUES('NE28', 'Novice Electronics');
INSERT INTO Courses VALUES('NP29', 'Novice Physical Education');
INSERT INTO Courses VALUES('NH30', 'Novice Health and Nutrition');
INSERT INTO Courses VALUES('NH31', 'Novice Home and Family Life Education');
INSERT INTO Courses VALUES('NC32', 'Novice Civics');
INSERT INTO Courses VALUES('NC33', 'Novice Carpentry');
INSERT INTO Courses VALUES('NW34', 'Novice Welding');
INSERT INTO Courses VALUES('NT35', 'Novice Telecommunications');
INSERT INTO Courses VALUES('NM36', 'Novice Machinery');
INSERT INTO Courses VALUES('NW37', 'Novice Web DEvelopement');
INSERT INTO Courses VALUES('ND38', 'Novice Database Management');
INSERT INTO Courses VALUES('ND39', 'Novice Discrete Mathematics');
INSERT INTO Courses VALUES('IP0', 'Intermediate Python');
INSERT INTO Courses VALUES('IJ1', 'Intermediate Javascript');
INSERT INTO Courses VALUES('IC2', 'Intermediate C#');
INSERT INTO Courses VALUES('IJ3', 'Intermediate Java');
INSERT INTO Courses VALUES('IC4', 'Intermediate C');
INSERT INTO Courses VALUES('IC5', 'Intermediate C++');
INSERT INTO Courses VALUES('IP6', 'Intermediate PHP');
INSERT INTO Courses VALUES('IK7', 'Intermediate Kotlin');
INSERT INTO Courses VALUES('IR8', 'Intermediate R');
INSERT INTO Courses VALUES('IH9', 'Intermediate HTML');
INSERT INTO Courses VALUES('IC10', 'Intermediate CSS');
INSERT INTO Courses VALUES('IS11', 'Intermediate Swift');
INSERT INTO Courses VALUES('IG12', 'Intermediate GO');
INSERT INTO Courses VALUES('IR13', 'Intermediate Ruby');
INSERT INTO Courses VALUES('IP14', 'Intermediate Pascal');
INSERT INTO Courses VALUES('ID15', 'Intermediate Dart');
INSERT INTO Courses VALUES('IP16', 'Intermediate Pascal');
INSERT INTO Courses VALUES('IR17', 'Intermediate Rust');
INSERT INTO Courses VALUES('IC18', 'Intermediate Cobol');
INSERT INTO Courses VALUES('IC19', 'Intermediate Calculus');
INSERT INTO Courses VALUES('IC20', 'Intermediate Calculus');
INSERT INTO Courses VALUES('IE21', 'Intermediate Electronic Circuit Analysis');
INSERT INTO Courses VALUES('IS22', 'Intermediate Statistics');
INSERT INTO Courses VALUES('IC23', 'Intermediate Chemistry');
INSERT INTO Courses VALUES('IB24', 'Intermediate Biology');
INSERT INTO Courses VALUES('IP25', 'Intermediate Physics');
INSERT INTO Courses VALUES('II26', 'Intermediate Information Technology');
INSERT INTO Courses VALUES('IC27', 'Intermediate Calculus 2');
INSERT INTO Courses VALUES('IE28', 'Intermediate Electronics');
INSERT INTO Courses VALUES('IP29', 'Intermediate Physical Education');
INSERT INTO Courses VALUES('IH30', 'Intermediate Health and Nutrition');
INSERT INTO Courses VALUES('IH31', 'Intermediate Home and Family Life Education');
INSERT INTO Courses VALUES('IC32', 'Intermediate Civics');
INSERT INTO Courses VALUES('IC33', 'Intermediate Carpentry');
INSERT INTO Courses VALUES('IW34', 'Intermediate Welding');
INSERT INTO Courses VALUES('IT35', 'Intermediate Telecommunications');
INSERT INTO Courses VALUES('IM36', 'Intermediate Machinery');
INSERT INTO Courses VALUES('IW37', 'Intermediate Web DEvelopement');
INSERT INTO Courses VALUES('ID38', 'Intermediate Database Management');
INSERT INTO Courses VALUES('ID39', 'Intermediate Discrete Mathematics');
INSERT INTO Courses VALUES('AP0', 'Advanced Python');
INSERT INTO Courses VALUES('AJ1', 'Advanced Javascript');
INSERT INTO Courses VALUES('AC2', 'Advanced C#');
INSERT INTO Courses VALUES('AJ3', 'Advanced Java');
INSERT INTO Courses VALUES('AC4', 'Advanced C');
INSERT INTO Courses VALUES('AC5', 'Advanced C++');
INSERT INTO Courses VALUES('AP6', 'Advanced PHP');
INSERT INTO Courses VALUES('AK7', 'Advanced Kotlin');
INSERT INTO Courses VALUES('AR8', 'Advanced R');
INSERT INTO Courses VALUES('AH9', 'Advanced HTML');
INSERT INTO Courses VALUES('AC10', 'Advanced CSS');
INSERT INTO Courses VALUES('AS11', 'Advanced Swift');
INSERT INTO Courses VALUES('AG12', 'Advanced GO');
INSERT INTO Courses VALUES('AR13', 'Advanced Ruby');
INSERT INTO Courses VALUES('AP14', 'Advanced Pascal');
INSERT INTO Courses VALUES('AD15', 'Advanced Dart');
INSERT INTO Courses VALUES('AP16', 'Advanced Pascal');
INSERT INTO Courses VALUES('AR17', 'Advanced Rust');
INSERT INTO Courses VALUES('AC18', 'Advanced Cobol');
INSERT INTO Courses VALUES('AC19', 'Advanced Calculus');
INSERT INTO Courses VALUES('AC20', 'Advanced Calculus');
INSERT INTO Courses VALUES('AE21', 'Advanced Electronic Circuit Analysis');
INSERT INTO Courses VALUES('AS22', 'Advanced Statistics');
INSERT INTO Courses VALUES('AC23', 'Advanced Chemistry');
INSERT INTO Courses VALUES('AB24', 'Advanced Biology');
INSERT INTO Courses VALUES('AP25', 'Advanced Physics');
INSERT INTO Courses VALUES('AI26', 'Advanced Information Technology');
INSERT INTO Courses VALUES('AC27', 'Advanced Calculus 2');
INSERT INTO Courses VALUES('AE28', 'Advanced Electronics');
INSERT INTO Courses VALUES('AP29', 'Advanced Physical Education');
INSERT INTO Courses VALUES('AH30', 'Advanced Health and Nutrition');
INSERT INTO Courses VALUES('AH31', 'Advanced Home and Family Life Education');
INSERT INTO Courses VALUES('AC32', 'Advanced Civics');
INSERT INTO Courses VALUES('AC33', 'Advanced Carpentry');
INSERT INTO Courses VALUES('AW34', 'Advanced Welding');
INSERT INTO Courses VALUES('AT35', 'Advanced Telecommunications');
INSERT INTO Courses VALUES('AM36', 'Advanced Machinery');
INSERT INTO Courses VALUES('AW37', 'Advanced Web DEvelopement');
INSERT INTO Courses VALUES('AD38', 'Advanced Database Management');
INSERT INTO Courses VALUES('AD39', 'Advanced Discrete Mathematics');
INSERT INTO Courses VALUES('EP0', 'Expert Python');
INSERT INTO Courses VALUES('EJ1', 'Expert Javascript');
INSERT INTO Courses VALUES('EC2', 'Expert C#');
INSERT INTO Courses VALUES('EJ3', 'Expert Java');
INSERT INTO Courses VALUES('EC4', 'Expert C');
INSERT INTO Courses VALUES('EC5', 'Expert C++');
INSERT INTO Courses VALUES('EP6', 'Expert PHP');
INSERT INTO Courses VALUES('EK7', 'Expert Kotlin');
INSERT INTO Courses VALUES('ER8', 'Expert R');
INSERT INTO Courses VALUES('EH9', 'Expert HTML');
INSERT INTO Courses VALUES('EC10', 'Expert CSS');
INSERT INTO Courses VALUES('ES11', 'Expert Swift');
INSERT INTO Courses VALUES('EG12', 'Expert GO');
INSERT INTO Courses VALUES('ER13', 'Expert Ruby');
INSERT INTO Courses VALUES('EP14', 'Expert Pascal');
INSERT INTO Courses VALUES('ED15', 'Expert Dart');
INSERT INTO Courses VALUES('EP16', 'Expert Pascal');
INSERT INTO Courses VALUES('ER17', 'Expert Rust');
INSERT INTO Courses VALUES('EC18', 'Expert Cobol');
INSERT INTO Courses VALUES('EC19', 'Expert Calculus');
INSERT INTO Courses VALUES('EC20', 'Expert Calculus');
INSERT INTO Courses VALUES('EE21', 'Expert Electronic Circuit Analysis');
INSERT INTO Courses VALUES('ES22', 'Expert Statistics');
INSERT INTO Courses VALUES('EC23', 'Expert Chemistry');
INSERT INTO Courses VALUES('EB24', 'Expert Biology');
INSERT INTO Courses VALUES('EP25', 'Expert Physics');
INSERT INTO Courses VALUES('EI26', 'Expert Information Technology');
INSERT INTO Courses VALUES('EC27', 'Expert Calculus 2');
INSERT INTO Courses VALUES('EE28', 'Expert Electronics');
INSERT INTO Courses VALUES('EP29', 'Expert Physical Education');
INSERT INTO Courses VALUES('EH30', 'Expert Health and Nutrition');
INSERT INTO Courses VALUES('EH31', 'Expert Home and Family Life Education');
INSERT INTO Courses VALUES('EC32', 'Expert Civics');
INSERT INTO Courses VALUES('EC33', 'Expert Carpentry');
INSERT INTO Courses VALUES('EW34', 'Expert Welding');
INSERT INTO Courses VALUES('ET35', 'Expert Telecommunications');
INSERT INTO Courses VALUES('EM36', 'Expert Machinery');
INSERT INTO Courses VALUES('EW37', 'Expert Web DEvelopement');
INSERT INTO Courses VALUES('ED38', 'Expert Database Management');
INSERT INTO Courses VALUES('ED39', 'Expert Discrete Mathematics');

INSERT INTO Students VALUES('S0', 'Darlene', 'Hernandez', 'Darlene.Hernandez@mymona.uwi.edu', 19, '2003-12-26', '9sRpBrWuo66DP');
INSERT INTO Students VALUES('S1', 'George', 'Cooper', 'George.Cooper@mymona.uwi.edu', 24, '1998-12-08', 'KlPRRofyAg');
INSERT INTO Students VALUES('S2', 'Christine', 'Ferguson', 'Christine.Ferguson@mymona.uwi.edu', 26, '1996-08-20', 'uaI6pNPFetfRMLy');
INSERT INTO Students VALUES('S3', 'James', 'Hudson', 'James.Hudson@mymona.uwi.edu', 20, '2002-04-12', 'ASNE1Q98OpK8B7t');
INSERT INTO Students VALUES('S4', 'Monica', 'Smith', 'Monica.Smith@mymona.uwi.edu', 27, '1995-09-19', '6uGuxse7D');
INSERT INTO Students VALUES('S5', 'Ana', 'Rollo', 'Ana.Rollo@mymona.uwi.edu', 22, '2000-06-10', 'ItsWyh5aDQMjj');
INSERT INTO Students VALUES('S6', 'Thomas', 'Mcphee', 'Thomas.Mcphee@mymona.uwi.edu', 25, '1998-02-02', 'AEb0Msec');
INSERT INTO Students VALUES('S7', 'Walter', 'Webb', 'Walter.Webb@mymona.uwi.edu', 18, '2005-02-16', 'hMenS9ekCuTYAvu');
INSERT INTO Students VALUES('S8', 'Edward', 'Hayes', 'Edward.Hayes@mymona.uwi.edu', 19, '2003-08-09', '3AqglINPB');
INSERT INTO Students VALUES('S9', 'Kathlene', 'Corral', 'Kathlene.Corral@mymona.uwi.edu', 19, '2003-04-15', 'XTm823BAx');

INSERT INTO Lecturers VALUES('L0', 'Deborah', 'Dupont', 'Deborah.Dupont@uwimona.edu.jm', 30, '1993-02-09', 'mVrrgKNqOm2t');
INSERT INTO Lecturers VALUES('L1', 'Dennis', 'Mann', 'Dennis.Mann@uwimona.edu.jm', 40, '1982-05-07', 'ErGc2nWVD9XPk7');
INSERT INTO Lecturers VALUES('L2', 'Tamara', 'Troutman', 'Tamara.Troutman@uwimona.edu.jm', 30, '1992-06-02', '7SHzKsnc34n2wY');
INSERT INTO Lecturers VALUES('L3', 'Sandra', 'Jackson', 'Sandra.Jackson@uwimona.edu.jm', 37, '1985-06-19', 'ymqSQZdgRKw6t87E');
INSERT INTO Lecturers VALUES('L4', 'Tobi', 'Campagna', 'Tobi.Campagna@uwimona.edu.jm', 33, '1990-02-26', 'QRa3dFxljV91rP9');
INSERT INTO Lecturers VALUES('L5', 'Richard', 'Meyerhofer', 'Richard.Meyerhofer@uwimona.edu.jm', 38, '1984-12-09', 'yRmqxds1y2O1P97');
INSERT INTO Lecturers VALUES('L6', 'Carrie', 'Wells', 'Carrie.Wells@uwimona.edu.jm', 40, '1982-10-06', '3LcKVRrACrCj1As');
INSERT INTO Lecturers VALUES('L7', 'Thomas', 'England', 'Thomas.England@uwimona.edu.jm', 31, '1991-07-04', 'jjRUvx40yIGy');
INSERT INTO Lecturers VALUES('L8', 'Kathryn', 'Farrell', 'Kathryn.Farrell@uwimona.edu.jm', 33, '1990-01-26', 'C3FAiqYyt4');
INSERT INTO Lecturers VALUES('L9', 'Wendy', 'Harnden', 'Wendy.Harnden@uwimona.edu.jm', 32, '1990-07-25', 'sHb3EE5CsW');
INSERT INTO Lecturers VALUES('L10', 'George', 'White', 'George.White@uwimona.edu.jm', 36, '1986-08-15', 'f8FtQGp3h');
INSERT INTO Lecturers VALUES('L11', 'Alan', 'Furfaro', 'Alan.Furfaro@uwimona.edu.jm', 38, '1985-03-08', 'zSRu0s0VOr9qFtPj');
INSERT INTO Lecturers VALUES('L12', 'Danielle', 'Smith', 'Danielle.Smith@uwimona.edu.jm', 36, '1987-01-07', 'RsQaUKJ9c1U');
INSERT INTO Lecturers VALUES('L13', 'Amy', 'Gonzales', 'Amy.Gonzales@uwimona.edu.jm', 37, '1985-04-28', 'ZpTXSRyqiV6jKhZ');
INSERT INTO Lecturers VALUES('L14', 'Robert', 'Shoulta', 'Robert.Shoulta@uwimona.edu.jm', 39, '1984-03-02', 'arc5aS99TlWEo9');
INSERT INTO Lecturers VALUES('L15', 'Rachel', 'Coryell', 'Rachel.Coryell@uwimona.edu.jm', 31, '1991-05-26', '63q6dA8w13csJq');
INSERT INTO Lecturers VALUES('L16', 'Rebecca', 'Smith', 'Rebecca.Smith@uwimona.edu.jm', 37, '1986-03-29', 'CPbhXN45');
INSERT INTO Lecturers VALUES('L17', 'Roger', 'Kennedy', 'Roger.Kennedy@uwimona.edu.jm', 32, '1990-09-17', 'EMMpAkPdHQpd');
INSERT INTO Lecturers VALUES('L18', 'Larry', 'Valone', 'Larry.Valone@uwimona.edu.jm', 37, '1985-06-30', 'RQUlaZs39EPetz');
INSERT INTO Lecturers VALUES('L19', 'Bernard', 'Pryor', 'Bernard.Pryor@uwimona.edu.jm', 37, '1986-02-25', 'wsvOo9maD');
INSERT INTO Lecturers VALUES('L20', 'Rachel', 'Logan', 'Rachel.Logan@uwimona.edu.jm', 40, '1982-12-21', 'ylyzCreFIAAvWL');
INSERT INTO Lecturers VALUES('L21', 'Adrian', 'Friend', 'Adrian.Friend@uwimona.edu.jm', 33, '1989-06-02', '0KPZTEc4QFGO');
INSERT INTO Lecturers VALUES('L22', 'Carlos', 'Lajoie', 'Carlos.Lajoie@uwimona.edu.jm', 31, '1992-01-10', 'FpQ5rTT206Yub');
INSERT INTO Lecturers VALUES('L23', 'Jason', 'Shepard', 'Jason.Shepard@uwimona.edu.jm', 38, '1984-09-04', 'CojOSzaIop');
INSERT INTO Lecturers VALUES('L24', 'John', 'Reiner', 'John.Reiner@uwimona.edu.jm', 36, '1987-01-20', 'k8AHL9aEjd');
INSERT INTO Lecturers VALUES('L25', 'Theodore', 'Hill', 'Theodore.Hill@uwimona.edu.jm', 31, '1991-05-14', 'XtOu9rvjEOt');
INSERT INTO Lecturers VALUES('L26', 'Robert', 'Whitson', 'Robert.Whitson@uwimona.edu.jm', 31, '1991-04-28', 'd2za1e1B');
INSERT INTO Lecturers VALUES('L27', 'Miranda', 'Ewing', 'Miranda.Ewing@uwimona.edu.jm', 35, '1987-12-15', 'VQNhus4ZHh');
INSERT INTO Lecturers VALUES('L28', 'Bonnie', 'Thomas', 'Bonnie.Thomas@uwimona.edu.jm', 36, '1987-01-19', '8lQULbtvPQMK');
INSERT INTO Lecturers VALUES('L29', 'Virginia', 'Pease', 'Virginia.Pease@uwimona.edu.jm', 38, '1984-06-17', 'iScsyXyYHzhaeZ');
INSERT INTO Lecturers VALUES('L30', 'Jimmie', 'Shaver', 'Jimmie.Shaver@uwimona.edu.jm', 31, '1991-10-12', 'R07vS0Kprzp');
INSERT INTO Lecturers VALUES('L31', 'Brenda', 'Tate', 'Brenda.Tate@uwimona.edu.jm', 39, '1983-11-12', 'V9cjc2kmko8g');
INSERT INTO Lecturers VALUES('L32', 'Terence', 'Jackson', 'Terence.Jackson@uwimona.edu.jm', 37, '1985-08-16', 'rfazIXw1Fks');
INSERT INTO Lecturers VALUES('L33', 'Michael', 'Diaz', 'Michael.Diaz@uwimona.edu.jm', 39, '1984-02-16', 'hGut727Erf');
INSERT INTO Lecturers VALUES('L34', 'Raymond', 'Lemmon', 'Raymond.Lemmon@uwimona.edu.jm', 32, '1990-09-07', 'Cj6fl396jFMQ7U');
INSERT INTO Lecturers VALUES('L35', 'Sara', 'Doolittle', 'Sara.Doolittle@uwimona.edu.jm', 34, '1988-08-25', 'J3AsQE83J1p5');
INSERT INTO Lecturers VALUES('L36', 'Terry', 'Metzger', 'Terry.Metzger@uwimona.edu.jm', 37, '1985-06-29', 'GcxurJM0xwF');
INSERT INTO Lecturers VALUES('L37', 'Wilford', 'Helms', 'Wilford.Helms@uwimona.edu.jm', 39, '1983-12-08', 'JCN17FLjuvR');
INSERT INTO Lecturers VALUES('L38', 'Emma', 'Mccloskey', 'Emma.Mccloskey@uwimona.edu.jm', 39, '1983-05-25', 'gMdcalAAqsqVUWJF');
INSERT INTO Lecturers VALUES('L39', 'Anthony', 'Mcatee', 'Anthony.Mcatee@uwimona.edu.jm', 39, '1983-05-03', 'f1JKDhWEF');
INSERT INTO Lecturers VALUES('L40', 'Linda', 'Bowles', 'Linda.Bowles@uwimona.edu.jm', 38, '1985-03-25', 'kklZDbWdXoO');
INSERT INTO Lecturers VALUES('L41', 'Elizabeth', 'Warner', 'Elizabeth.Warner@uwimona.edu.jm', 38, '1984-06-03', 'dkwTtFuj0jKNqcYO');
INSERT INTO Lecturers VALUES('L42', 'Stacey', 'Anderson', 'Stacey.Anderson@uwimona.edu.jm', 32, '1991-01-17', 'uBT9e0Q13l');
INSERT INTO Lecturers VALUES('L43', 'Cassandra', 'Quade', 'Cassandra.Quade@uwimona.edu.jm', 39, '1984-02-27', 'nIp44T66d');
INSERT INTO Lecturers VALUES('L44', 'John', 'Presswood', 'John.Presswood@uwimona.edu.jm', 39, '1984-02-03', 'Z7abEsEKHblJ6J');
INSERT INTO Lecturers VALUES('L45', 'Adrian', 'Khatri', 'Adrian.Khatri@uwimona.edu.jm', 32, '1990-06-27', 'qQYGsBORMvCOZyt');
INSERT INTO Lecturers VALUES('L46', 'Diane', 'Walker', 'Diane.Walker@uwimona.edu.jm', 30, '1992-05-21', 'i20Tsi6KMuA');
INSERT INTO Lecturers VALUES('L47', 'Christopher', 'Summers', 'Christopher.Summers@uwimona.edu.jm', 38, '1984-05-08', 'BxFppkIbUpMQLhMI');
INSERT INTO Lecturers VALUES('L48', 'Tiffany', 'Shaw', 'Tiffany.Shaw@uwimona.edu.jm', 34, '1988-12-11', '6YPRCrmStPGA');
INSERT INTO Lecturers VALUES('L49', 'Marian', 'Triplett', 'Marian.Triplett@uwimona.edu.jm', 38, '1984-12-26', 'kvREMKYCvxbRu4');
INSERT INTO Lecturers VALUES('L50', 'Warren', 'Hawkins', 'Warren.Hawkins@uwimona.edu.jm', 33, '1990-04-04', 'an8IcjSYt');
INSERT INTO Lecturers VALUES('L51', 'Robert', 'Yowell', 'Robert.Yowell@uwimona.edu.jm', 35, '1987-06-07', 'mH7zA0jS');
INSERT INTO Lecturers VALUES('L52', 'Shelia', 'Bennett', 'Shelia.Bennett@uwimona.edu.jm', 40, '1982-09-09', 'yYC1vIrBnLQu');
INSERT INTO Lecturers VALUES('L53', 'Lottie', 'Webb', 'Lottie.Webb@uwimona.edu.jm', 30, '1992-05-19', 'tw74rbUD');
INSERT INTO Lecturers VALUES('L54', 'David', 'Michael', 'David.Michael@uwimona.edu.jm', 40, '1983-02-20', 'z1jYnFl5C6PuPA');
INSERT INTO Lecturers VALUES('L55', 'David', 'Gabriel', 'David.Gabriel@uwimona.edu.jm', 38, '1984-07-06', 'I8WH4hin6Vl');
INSERT INTO Lecturers VALUES('L56', 'Robert', 'Dacus', 'Robert.Dacus@uwimona.edu.jm', 31, '1991-12-18', 'gU7Fhkj7uG1hUt');
INSERT INTO Lecturers VALUES('L57', 'Lissa', 'Crumrine', 'Lissa.Crumrine@uwimona.edu.jm', 37, '1985-10-09', 'Ma0hibKU4');
INSERT INTO Lecturers VALUES('L58', 'James', 'Dias', 'James.Dias@uwimona.edu.jm', 40, '1982-12-04', 'tKnmWQQLP4xpm');
INSERT INTO Lecturers VALUES('L59', 'Yvonne', 'Johnson', 'Yvonne.Johnson@uwimona.edu.jm', 36, '1986-07-15', 'NuQwTIcIuh3CtB');

INSERT INTO `Course Lecturers` VALUES('L0', 'FP0');
INSERT INTO `Course Lecturers` VALUES('L1', 'FJ1');
INSERT INTO `Course Lecturers` VALUES('L2', 'FC2');
INSERT INTO `Course Lecturers` VALUES('L3', 'FJ3');
INSERT INTO `Course Lecturers` VALUES('L4', 'FC4');
INSERT INTO `Course Lecturers` VALUES('L5', 'FC5');
INSERT INTO `Course Lecturers` VALUES('L6', 'FP6');
INSERT INTO `Course Lecturers` VALUES('L7', 'FK7');
INSERT INTO `Course Lecturers` VALUES('L8', 'FR8');
INSERT INTO `Course Lecturers` VALUES('L9', 'FH9');
INSERT INTO `Course Lecturers` VALUES('L10', 'FC10');
INSERT INTO `Course Lecturers` VALUES('L10', 'FS11');
INSERT INTO `Course Lecturers` VALUES('L11', 'FG12');
INSERT INTO `Course Lecturers` VALUES('L11', 'FR13');
INSERT INTO `Course Lecturers` VALUES('L12', 'FP14');
INSERT INTO `Course Lecturers` VALUES('L12', 'FD15');
INSERT INTO `Course Lecturers` VALUES('L13', 'FP16');
INSERT INTO `Course Lecturers` VALUES('L13', 'FR17');
INSERT INTO `Course Lecturers` VALUES('L14', 'FC18');
INSERT INTO `Course Lecturers` VALUES('L14', 'FC19');
INSERT INTO `Course Lecturers` VALUES('L15', 'FC20');
INSERT INTO `Course Lecturers` VALUES('L15', 'FE21');
INSERT INTO `Course Lecturers` VALUES('L16', 'FS22');
INSERT INTO `Course Lecturers` VALUES('L16', 'FC23');
INSERT INTO `Course Lecturers` VALUES('L17', 'FB24');
INSERT INTO `Course Lecturers` VALUES('L17', 'FP25');
INSERT INTO `Course Lecturers` VALUES('L18', 'FI26');
INSERT INTO `Course Lecturers` VALUES('L18', 'FC27');
INSERT INTO `Course Lecturers` VALUES('L19', 'FE28');
INSERT INTO `Course Lecturers` VALUES('L19', 'FP29');
INSERT INTO `Course Lecturers` VALUES('L20', 'FH30');
INSERT INTO `Course Lecturers` VALUES('L20', 'FH31');
INSERT INTO `Course Lecturers` VALUES('L20', 'FC32');
INSERT INTO `Course Lecturers` VALUES('L21', 'FC33');
INSERT INTO `Course Lecturers` VALUES('L21', 'FW34');
INSERT INTO `Course Lecturers` VALUES('L21', 'FT35');
INSERT INTO `Course Lecturers` VALUES('L22', 'FM36');
INSERT INTO `Course Lecturers` VALUES('L22', 'FW37');
INSERT INTO `Course Lecturers` VALUES('L22', 'FD38');
INSERT INTO `Course Lecturers` VALUES('L23', 'FD39');
INSERT INTO `Course Lecturers` VALUES('L23', 'NP0');
INSERT INTO `Course Lecturers` VALUES('L23', 'NJ1');
INSERT INTO `Course Lecturers` VALUES('L24', 'NC2');
INSERT INTO `Course Lecturers` VALUES('L24', 'NJ3');
INSERT INTO `Course Lecturers` VALUES('L24', 'NC4');
INSERT INTO `Course Lecturers` VALUES('L25', 'NC5');
INSERT INTO `Course Lecturers` VALUES('L25', 'NP6');
INSERT INTO `Course Lecturers` VALUES('L25', 'NK7');
INSERT INTO `Course Lecturers` VALUES('L26', 'NR8');
INSERT INTO `Course Lecturers` VALUES('L26', 'NH9');
INSERT INTO `Course Lecturers` VALUES('L26', 'NC10');
INSERT INTO `Course Lecturers` VALUES('L27', 'NS11');
INSERT INTO `Course Lecturers` VALUES('L27', 'NG12');
INSERT INTO `Course Lecturers` VALUES('L27', 'NR13');
INSERT INTO `Course Lecturers` VALUES('L28', 'NP14');
INSERT INTO `Course Lecturers` VALUES('L28', 'ND15');
INSERT INTO `Course Lecturers` VALUES('L28', 'NP16');
INSERT INTO `Course Lecturers` VALUES('L29', 'NR17');
INSERT INTO `Course Lecturers` VALUES('L29', 'NC18');
INSERT INTO `Course Lecturers` VALUES('L29', 'NC19');
INSERT INTO `Course Lecturers` VALUES('L30', 'NC20');
INSERT INTO `Course Lecturers` VALUES('L30', 'NE21');
INSERT INTO `Course Lecturers` VALUES('L30', 'NS22');
INSERT INTO `Course Lecturers` VALUES('L30', 'NC23');
INSERT INTO `Course Lecturers` VALUES('L31', 'NB24');
INSERT INTO `Course Lecturers` VALUES('L31', 'NP25');
INSERT INTO `Course Lecturers` VALUES('L31', 'NI26');
INSERT INTO `Course Lecturers` VALUES('L31', 'NC27');
INSERT INTO `Course Lecturers` VALUES('L32', 'NE28');
INSERT INTO `Course Lecturers` VALUES('L32', 'NP29');
INSERT INTO `Course Lecturers` VALUES('L32', 'NH30');
INSERT INTO `Course Lecturers` VALUES('L32', 'NH31');
INSERT INTO `Course Lecturers` VALUES('L33', 'NC32');
INSERT INTO `Course Lecturers` VALUES('L33', 'NC33');
INSERT INTO `Course Lecturers` VALUES('L33', 'NW34');
INSERT INTO `Course Lecturers` VALUES('L33', 'NT35');
INSERT INTO `Course Lecturers` VALUES('L34', 'NM36');
INSERT INTO `Course Lecturers` VALUES('L34', 'NW37');
INSERT INTO `Course Lecturers` VALUES('L34', 'ND38');
INSERT INTO `Course Lecturers` VALUES('L34', 'ND39');
INSERT INTO `Course Lecturers` VALUES('L35', 'IP0');
INSERT INTO `Course Lecturers` VALUES('L35', 'IJ1');
INSERT INTO `Course Lecturers` VALUES('L35', 'IC2');
INSERT INTO `Course Lecturers` VALUES('L35', 'IJ3');
INSERT INTO `Course Lecturers` VALUES('L36', 'IC4');
INSERT INTO `Course Lecturers` VALUES('L36', 'IC5');
INSERT INTO `Course Lecturers` VALUES('L36', 'IP6');
INSERT INTO `Course Lecturers` VALUES('L36', 'IK7');
INSERT INTO `Course Lecturers` VALUES('L37', 'IR8');
INSERT INTO `Course Lecturers` VALUES('L37', 'IH9');
INSERT INTO `Course Lecturers` VALUES('L37', 'IC10');
INSERT INTO `Course Lecturers` VALUES('L37', 'IS11');
INSERT INTO `Course Lecturers` VALUES('L38', 'IG12');
INSERT INTO `Course Lecturers` VALUES('L38', 'IR13');
INSERT INTO `Course Lecturers` VALUES('L38', 'IP14');
INSERT INTO `Course Lecturers` VALUES('L38', 'ID15');
INSERT INTO `Course Lecturers` VALUES('L39', 'IP16');
INSERT INTO `Course Lecturers` VALUES('L39', 'IR17');
INSERT INTO `Course Lecturers` VALUES('L39', 'IC18');
INSERT INTO `Course Lecturers` VALUES('L39', 'IC19');
INSERT INTO `Course Lecturers` VALUES('L40', 'IC20');
INSERT INTO `Course Lecturers` VALUES('L40', 'IE21');
INSERT INTO `Course Lecturers` VALUES('L40', 'IS22');
INSERT INTO `Course Lecturers` VALUES('L40', 'IC23');
INSERT INTO `Course Lecturers` VALUES('L40', 'IB24');
INSERT INTO `Course Lecturers` VALUES('L41', 'IP25');
INSERT INTO `Course Lecturers` VALUES('L41', 'II26');
INSERT INTO `Course Lecturers` VALUES('L41', 'IC27');
INSERT INTO `Course Lecturers` VALUES('L41', 'IE28');
INSERT INTO `Course Lecturers` VALUES('L41', 'IP29');
INSERT INTO `Course Lecturers` VALUES('L42', 'IH30');
INSERT INTO `Course Lecturers` VALUES('L42', 'IH31');
INSERT INTO `Course Lecturers` VALUES('L42', 'IC32');
INSERT INTO `Course Lecturers` VALUES('L42', 'IC33');
INSERT INTO `Course Lecturers` VALUES('L42', 'IW34');
INSERT INTO `Course Lecturers` VALUES('L43', 'IT35');
INSERT INTO `Course Lecturers` VALUES('L43', 'IM36');
INSERT INTO `Course Lecturers` VALUES('L43', 'IW37');
INSERT INTO `Course Lecturers` VALUES('L43', 'ID38');
INSERT INTO `Course Lecturers` VALUES('L43', 'ID39');
INSERT INTO `Course Lecturers` VALUES('L44', 'AP0');
INSERT INTO `Course Lecturers` VALUES('L44', 'AJ1');
INSERT INTO `Course Lecturers` VALUES('L44', 'AC2');
INSERT INTO `Course Lecturers` VALUES('L44', 'AJ3');
INSERT INTO `Course Lecturers` VALUES('L44', 'AC4');
INSERT INTO `Course Lecturers` VALUES('L45', 'AC5');
INSERT INTO `Course Lecturers` VALUES('L45', 'AP6');
INSERT INTO `Course Lecturers` VALUES('L45', 'AK7');
INSERT INTO `Course Lecturers` VALUES('L45', 'AR8');
INSERT INTO `Course Lecturers` VALUES('L45', 'AH9');
INSERT INTO `Course Lecturers` VALUES('L46', 'AC10');
INSERT INTO `Course Lecturers` VALUES('L46', 'AS11');
INSERT INTO `Course Lecturers` VALUES('L46', 'AG12');
INSERT INTO `Course Lecturers` VALUES('L46', 'AR13');
INSERT INTO `Course Lecturers` VALUES('L46', 'AP14');
INSERT INTO `Course Lecturers` VALUES('L47', 'AD15');
INSERT INTO `Course Lecturers` VALUES('L47', 'AP16');
INSERT INTO `Course Lecturers` VALUES('L47', 'AR17');
INSERT INTO `Course Lecturers` VALUES('L47', 'AC18');
INSERT INTO `Course Lecturers` VALUES('L47', 'AC19');
INSERT INTO `Course Lecturers` VALUES('L48', 'AC20');
INSERT INTO `Course Lecturers` VALUES('L48', 'AE21');
INSERT INTO `Course Lecturers` VALUES('L48', 'AS22');
INSERT INTO `Course Lecturers` VALUES('L48', 'AC23');
INSERT INTO `Course Lecturers` VALUES('L48', 'AB24');
INSERT INTO `Course Lecturers` VALUES('L49', 'AP25');
INSERT INTO `Course Lecturers` VALUES('L49', 'AI26');
INSERT INTO `Course Lecturers` VALUES('L49', 'AC27');
INSERT INTO `Course Lecturers` VALUES('L49', 'AE28');
INSERT INTO `Course Lecturers` VALUES('L49', 'AP29');
INSERT INTO `Course Lecturers` VALUES('L50', 'AH30');
INSERT INTO `Course Lecturers` VALUES('L50', 'AH31');
INSERT INTO `Course Lecturers` VALUES('L50', 'AC32');
INSERT INTO `Course Lecturers` VALUES('L50', 'AC33');
INSERT INTO `Course Lecturers` VALUES('L50', 'AW34');
INSERT INTO `Course Lecturers` VALUES('L51', 'AT35');
INSERT INTO `Course Lecturers` VALUES('L51', 'AM36');
INSERT INTO `Course Lecturers` VALUES('L51', 'AW37');
INSERT INTO `Course Lecturers` VALUES('L51', 'AD38');
INSERT INTO `Course Lecturers` VALUES('L51', 'AD39');
INSERT INTO `Course Lecturers` VALUES('L52', 'EP0');
INSERT INTO `Course Lecturers` VALUES('L52', 'EJ1');
INSERT INTO `Course Lecturers` VALUES('L52', 'EC2');
INSERT INTO `Course Lecturers` VALUES('L52', 'EJ3');
INSERT INTO `Course Lecturers` VALUES('L52', 'EC4');
INSERT INTO `Course Lecturers` VALUES('L53', 'EC5');
INSERT INTO `Course Lecturers` VALUES('L53', 'EP6');
INSERT INTO `Course Lecturers` VALUES('L53', 'EK7');
INSERT INTO `Course Lecturers` VALUES('L53', 'ER8');
INSERT INTO `Course Lecturers` VALUES('L53', 'EH9');
INSERT INTO `Course Lecturers` VALUES('L54', 'EC10');
INSERT INTO `Course Lecturers` VALUES('L54', 'ES11');
INSERT INTO `Course Lecturers` VALUES('L54', 'EG12');
INSERT INTO `Course Lecturers` VALUES('L54', 'ER13');
INSERT INTO `Course Lecturers` VALUES('L54', 'EP14');
INSERT INTO `Course Lecturers` VALUES('L55', 'ED15');
INSERT INTO `Course Lecturers` VALUES('L55', 'EP16');
INSERT INTO `Course Lecturers` VALUES('L55', 'ER17');
INSERT INTO `Course Lecturers` VALUES('L55', 'EC18');
INSERT INTO `Course Lecturers` VALUES('L55', 'EC19');
INSERT INTO `Course Lecturers` VALUES('L56', 'EC20');
INSERT INTO `Course Lecturers` VALUES('L56', 'EE21');
INSERT INTO `Course Lecturers` VALUES('L56', 'ES22');
INSERT INTO `Course Lecturers` VALUES('L56', 'EC23');
INSERT INTO `Course Lecturers` VALUES('L56', 'EB24');
INSERT INTO `Course Lecturers` VALUES('L57', 'EP25');
INSERT INTO `Course Lecturers` VALUES('L57', 'EI26');
INSERT INTO `Course Lecturers` VALUES('L57', 'EC27');
INSERT INTO `Course Lecturers` VALUES('L57', 'EE28');
INSERT INTO `Course Lecturers` VALUES('L57', 'EP29');
INSERT INTO `Course Lecturers` VALUES('L58', 'EH30');
INSERT INTO `Course Lecturers` VALUES('L58', 'EH31');
INSERT INTO `Course Lecturers` VALUES('L58', 'EC32');
INSERT INTO `Course Lecturers` VALUES('L58', 'EC33');
INSERT INTO `Course Lecturers` VALUES('L58', 'EW34');
INSERT INTO `Course Lecturers` VALUES('L59', 'ET35');
INSERT INTO `Course Lecturers` VALUES('L59', 'EM36');
INSERT INTO `Course Lecturers` VALUES('L59', 'EW37');
INSERT INTO `Course Lecturers` VALUES('L59', 'ED38');
INSERT INTO `Course Lecturers` VALUES('L59', 'ED39');
